name: Meeting
description: Create meeting notes 🚀
title: "[Meeting] <title>"
labels: ["meeting"]
body:
- type: markdown
  attributes:
    label: 🙋 Participants
    description: Mention the participants who attended the meeting.
  validations:
    required: true
- type: markdown
  attributes:
    label: 📍 Meeting location
    description: Where the meeting was held.
  validations:
    required: true
- type: markwdown
  attributes:
    label: 🗓️ Meeting date and time
    description: Date and time when the meeting started.
  validations:
    required: true
- type: markdown
  attributes:
    label: ⏳ Meeting duration estimate
    description: Estimate how long the meeting will take.
  validations:
    required: true
- type: markdown
  attributes:
    label: 📋 Meeting agenda
    description: Break down the meeting topics, talking points, and agenda items.
  validations:
    required: true
- type: markdown
  attributes:
    label: 🚀 Meeting updates
    description: Summarize the exciting updates and discussions from the meeting.
  validations:
    required: false
- type: markdown
  attributes:
    label: 📝 Meeting action items
    description: List the action items assigned during the meeting.
  validations:
    required: false
- type: markdown
  attributes:
    label: 🌟 Meeting wrap-up
    description: Closing remarks, schedule the next meeting, and record the adjournment time.
  validations:
    required: false
